### ISSUE TITLE
While Loops Challenge 30:  Power Ball Simulator App

### ISSUE THREAD

**Issue by michael-b-tt0** [PacktPublishing/The-Art-of-Doing-Code-40-Challenging-Python-Programs-Today#1]
if lottery_numbers not in tickets_sold:
        tickets_purchased += 1
        tickets_sold.append(lottery_numbers)
        print(lottery_numbers)
    #The ticket has already been sold and is a loser; don't sell again
    else:
        print("Losing ticket generated; disregard...")

    
    if tickets_purchased % ticket_interval == 0:
        print(str(tickets_purchased) + " tickets purchased so far with no winners...")
        choice = input("\nKeep purchasing tickets (y/n): ")
        if choice != 'y':
            active = False`

The if tickets_purchased % ticket_interval == 0: will pass true if the first lottery number generated that cycle is in tickets sold and tickets purchased is stuck at its previous value thus ending the loop before any tickets have been purchased.

**Comment by Sonakshis** [comment]
First, You need to create a new variable, "round_first_sold" and initialize it to false.  This will happen right before the main while loop of the program.

#initialize variables to aid in the selling of tickets
tickets_purchased = 0
active = True
tickets_sold = []
round_first_sold = False

Next, when the generated ticket is actually purchased, inside the if statement we will set the round_first_sold variable to True because the first ticket in a given round has officially be sold.

    #This current ticket has not yet been sold
    if lottery_numbers not in tickets_sold:
        tickets_purchased += 1
        tickets_sold.append(lottery_numbers)
        print(lottery_numbers)
        round_first_sold = True

Now, when we check to see if the user wants to continue to buy at the given ticket interval, we will also check that the round_first_sold variable is True.  This should prevent the premature triggering of this statement on the chance of a repeat ticket on the first iteration of our loop.  We then have to set the round_first_sold variable back to False as a new round will be starting.

    #Check if the user wants to continue buying tickets at the indicated interval
    if tickets_purchased % ticket_interval == 0 and round_first_sold == True:
        round_first_sold = False
        print(str(tickets_purchased) + " tickets purchased so far with no winners...")
        choice = input("\nKeep purchasing tickets (y/n): ")
        if choice != 'y':
            active = False
        else:
            continue

That should fix the issue.
